# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cawcaw"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kenji Hara"]
  s.date = "2013-01-01"
  s.description = "cawcaw RubyGem"
  s.email = "haracane@gmail.com"
  s.executables = ["cawcaw"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/cawcaw",
    "lib/cawcaw.rb",
    "lib/cawcaw/command/hadoop.rb",
    "lib/cawcaw/command/hadoop/dfs.rb",
    "lib/cawcaw/command/rabbitmq.rb",
    "lib/cawcaw/command/rabbitmq/queue_count.rb",
    "lib/cawcaw/core/common.rb",
    "spec/lib/cawcaw_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/haracane/cawcaw"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "cawcaw RubyGem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bunnish>, [">= 0.1.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_development_dependency(%q<ci_reporter>, [">= 1.7.0"])
      s.add_development_dependency(%q<flog>, [">= 3.2.0"])
    else
      s.add_dependency(%q<bunnish>, [">= 0.1.0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_dependency(%q<ci_reporter>, [">= 1.7.0"])
      s.add_dependency(%q<flog>, [">= 3.2.0"])
    end
  else
    s.add_dependency(%q<bunnish>, [">= 0.1.0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<simplecov-rcov>, [">= 0"])
    s.add_dependency(%q<ci_reporter>, [">= 1.7.0"])
    s.add_dependency(%q<flog>, [">= 3.2.0"])
  end
end

